description: |
 Config file for downstream analyses of the KPlung data
author: "Aur√©lie Gabriel"

analysis_folder: /work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/results_human_data_4samples/
snakemake_path: /work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/
input_data_path: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/input_data/'
human_data:
  fasta_file: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/results/PEPATAC_processing/genome_folder/data/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta/default/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa'
  counts: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/results/PEPATAC_processing/Human_data/consensus_peaks/raw_counts.txt'
  metadata: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/results/PEPATAC_processing/Human_data/consensus_peaks/metadata.txt'
  pfm_file: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/input_data/H12CORE_human_pfm.rds'
  motif_annotations: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/input_data/HOCOMOCO_v12_annotation_human.txt'
  homer_motifs_file: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/snakemake_pipeline/input_data/homer_motifs_file_human.txt'
  gtf: '/work/FAC/FBM/LLB/dgfeller/scrnaseq/agabrie4/collaborations/Mate_Pittet_lab/results/PEPATAC_processing/genome_folder/data/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/ensembl_gtf/default/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.gtf.gz'

PCA_samplesCorrelation:
  cpus-per-task: 1
  mem_mb: 8000
  time: '1:00:00'
PCA_chromVAR:
  cpus-per-task: 1
  mem_mb: 64000
  time: '1:00:00'

run_chromVAR:
  cpus-per-task: 5
  mem_mb: 64000
  time: '1:00:00'

DAR_HOMER:
  cpus-per-task: 1
  mem_mb: 8000
  time: '1:00:00'

merge_bams:
  cpus-per-task: 10
  mem_mb: 10000
  time: '2:00:00'

footprinting:
  cpus-per-task: 20
  mem_mb: 10000
  time: '7:00:00'

pathway_enrichment:
  cpus-per-task: 10
  mem_mb: 20000
  time: '2:00:00'

motif_enrichment_HOMER:
  cpus-per-task: 10
  mem_mb: 64000
  time: '2:00:00'

atlases_signatures:
  cpus-per-task: 1
  mem_mb: 64000
  time: '1:00:00'


get_fragments:
  cpus-per-task: 10
  mem_mb: 50000
  time: '2:00:00'

get_gene_activity:
  cpus-per-task: 10
  mem_mb: 100000
  time: '3:00:00'

diff_footprinting:
  cpus-per-task: 20
  mem_mb: 10000
  time: '2:00:00'

gsva_run:
  cpus-per-task: 1
  mem_mb: 64000
  time: '1:00:00'

addChromatinModule:
  cpus-per-task: 5
  mem_mb: 64000
  time: '1:00:00'
