cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
restart-times: 0 # this will allow to re-run a job 3 time maximum if it fails (usefull if we specify in the rule to increase memory in each attempt)
latency-wait: 120
jobs: 500 # to say that we wwant that a maximum of 100 jobs are launched on the cluster
keep-going: True  #Go on with independent jobs if a job fails
rerun-incomplete: True  #Re-run all jobs the output of which is recognized as incomplete
printshellcmds: True  #Print out the shell commands that will be executed
use-apptainer: True
executor: cluster-generic
apptainer-args: '--bind /work,/scratch,/users/agabrie4/'

default-resources:
  mem_mb: 8000
  time: 60
